/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

import AudioDriver from "../utils/audioDriver";

// @ts-ignore
import uri from "../assets/models/radio.glb";
// @ts-ignore
import music from "../assets/audio/btlalc_radio.wav";

type GLTFResult = GLTF & {
  nodes: {
    obj_1: THREE.Mesh;
    obj_3: THREE.Mesh;
    obj_5: THREE.Mesh;
    obj_7: THREE.Mesh;
    obj_2: THREE.Mesh;
    obj_8: THREE.Mesh;
    obj_8_1: THREE.Mesh;
    obj_8_2: THREE.Mesh;
    obj_8_3: THREE.Mesh;
    obj_8_4: THREE.Mesh;
    obj_9: THREE.Mesh;
    obj_10: THREE.Mesh;
    obj_4: THREE.Mesh;
    obj_4_1: THREE.Mesh;
    obj_6: THREE.Mesh;
    obj_11: THREE.Mesh;
  };
  materials: {
    ["Mat.7"]: THREE.MeshStandardMaterial;
    ["Mat.3"]: THREE.MeshStandardMaterial;
    ["Mat.1"]: THREE.MeshStandardMaterial;
    ["Mat.5.1"]: THREE.MeshStandardMaterial;
    ["Mat.5"]: THREE.MeshStandardMaterial;
    ["Mat.1"]: THREE.MeshStandardMaterial;
    ["Mat.7.1"]: THREE.MeshStandardMaterial;
    ["Mat.5"]: THREE.MeshStandardMaterial;
    ["Mat.1.1"]: THREE.MeshStandardMaterial;
    ["Mat.7.2"]: THREE.MeshStandardMaterial;
    ["Mat.5.2"]: THREE.MeshStandardMaterial;
    ["Mat.5.3"]: THREE.MeshStandardMaterial;
    ["Mat.4"]: THREE.MeshStandardMaterial;
    Mat: THREE.MeshStandardMaterial;
    ["Mat.1"]: THREE.MeshStandardMaterial;
    ["Mat.2"]: THREE.MeshStandardMaterial;
    decor: THREE.MeshStandardMaterial;
    ["Mat.2"]: THREE.MeshStandardMaterial;
  };
};

export default function Model({ ...props }: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>();
  const { nodes, materials } = useGLTF(uri) as GLTFResult;
  return (
    <group ref={group} {...props} dispose={null} scale={[0.6, 0.6, 0.6]}>
      <mesh geometry={nodes.obj_1.geometry} material={materials["Mat.7"]} />
      <mesh geometry={nodes.obj_3.geometry} material={materials["Mat.3"]} />
      <mesh geometry={nodes.obj_5.geometry} material={nodes.obj_5.material} />
      <mesh geometry={nodes.obj_7.geometry} material={materials["Mat.5.1"]} />
      <mesh geometry={nodes.obj_2.geometry} material={nodes.obj_2.material} />
      <mesh geometry={nodes.obj_8.geometry} material={nodes.obj_8.material} />
      <mesh geometry={nodes.obj_8_1.geometry} material={materials["Mat.7.1"]} />
      <mesh
        geometry={nodes.obj_8_2.geometry}
        material={nodes.obj_8_2.material}
      />
      <mesh geometry={nodes.obj_8_3.geometry} material={materials["Mat.1.1"]} />
      <mesh geometry={nodes.obj_8_4.geometry} material={materials["Mat.7.2"]} />
      <mesh geometry={nodes.obj_9.geometry} material={materials["Mat.5.2"]} />
      <mesh geometry={nodes.obj_10.geometry} material={materials["Mat.5.3"]} />
      <mesh geometry={nodes.obj_4.geometry} material={materials["Mat.4"]} />
      <mesh geometry={nodes.obj_4_1.geometry} material={materials.Mat} />
      <mesh geometry={nodes.obj_6.geometry} material={nodes.obj_6.material} />
      <mesh geometry={nodes.obj_11.geometry} material={nodes.obj_11.material} />
      <AudioDriver url={music} volume={10} />
    </group>
  );
}

useGLTF.preload(uri);
